- name: configure httpd on centos 7
  hosts: localhost
  become: yes
  become_method: su
  tasks:
     - name: install packages
       yum: name=php-mysql state=latest
     - name: install httpd
       yum: name=httpd state=present
     - name: altering httpd for  php
       replace:
        path: /etc/httpd/conf/httpd.conf
        regexp: 'DirectoryIndex index.html'
        replace: "DirectoryIndex index.php"
        backup: yes
     - name: Enabled httpd and start
       systemd: name=httpd enabled=yes state=started
     - name: Install git
       yum: name=git state=latest
     - name: get git files
       git:
        repo: https://github.com/kodekloudhub/learning-app-ecommerce.git
        dest: /var/www/html
        update: no
     - name: update the index.php file
       replace:
        path: /var/www/html/index.php
        regexp: "$link = mysqli_connect('172.20.1.101', 'ecomuser', 'ecompassword', 'ecomdb');"
        replace: "$link = mysqli_connect('localhost', 'root', 'osboxes.org', 'ecomdb');"
        backup: yes
     - name: restart httpd instace
       service: name=httpd state=restarted
